routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'PageController@about')->name('about');
Route::post('/about',  'PageController@about')->name('about');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => ['web']], function () {
        Route::resource('material', 'MaterialController');
        Route::resource('business_partners', 'Business_PartnersController');
        Route::resource('business_partner_documents', 'Business_Partner_DocumentsController');
        Route::resource('material_measures', 'Material_MeasuresController');
        Route::resource('material_providers', 'Material_ProvidersController');
        Route::resource('stocks', 'StocksController');
               
        Route::group(['middleware' => ['caffeinated']], function () {
            Route::resource('prices_list', 'Prices_ListController');
            Route::resource('good_entry', 'Good_EntryController');
            Route::resource('detail_good_entry', 'Detail_Good_EntryController');            
            Route::resource('delivery_order', 'Delivery_OrderController');
            Route::resource('detail_delivery_order', 'Detail_Delivery_OrderController');
            Route::get('data-goods-entries', 'Good_EntryController@dataGoodsEntries')->name('good_entry.dataGoodsEntries');
            Route::get('data-delivery-orders', 'Delivery_OrderController@dataDeliveryOrders')->name('delivery_order.dataDeliveryOrders');
            Route::get('add-provider', 'Good_EntryController@addProvider')->name('good_entry.addProvider');
            Route::get('add-customer', 'Delivery_OrderController@addCustomer')->name('delivery_order.addCustomer');
            Route::get('providers-autocomplete', 'Good_EntryController@dataProviders')->name('good_entry.providers-autocomplete');
            Route::get('customers-autocomplete', 'Delivery_OrderController@dataCustomers')->name('delivery_order.customers-autocomplete');
            Route::get('detail_good_entry-materials-autocomplete', 'Detail_Good_EntryController@dataMaterials')->name('detail_good_entry.materials-autocomplete');
            Route::get('detail_delivery_order-materials-autocomplete', 'Detail_Delivery_OrderController@dataMaterials')->name('detail_delivery_order.materials-autocomplete');
            Route::get('detail_delivery_order-material-measures-autocomplete', 'Detail_Delivery_OrderController@dataMeasures')->name('detail_delivery_order.material-measures-autocomplete');
            Route::get('process-goods-entry', 'Good_EntryController@process')->name('good_entry.process');
            Route::get('process-delivery-order', 'Delivery_OrderController@process')->name('delivery_order.process');
        });

    });    

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/Detail_Delivery_Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Detail_Delivery_Order extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'detail_delivery_orders';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['delivery_order_id', 'material_id','measure_id', 'quantity', 'price', 'subtotal'];

    use SoftDeletes;
    protected $dates = ['deleted_at'];

    public function delivery_order()
    {
        return $this->belongsTo('App\Delivery_Order','delivery_order_id');
    }

    public function material() {
        return $this->belongsTo('App\Material','material_id');
    }

    public function measure() {
        return $this->belongsTo('App\Measure','measure_id');
    }    

}

app/Http/Controllers/Detail_Delivery_OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Helpers\PreviousRoute;
use App\Detail_Delivery_Order;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Session;
use DB;

class Detail_Delivery_OrderController extends Controller
{

    /**
     * Define your validation rules in a property in
     * the controller to reuse the rules.
     */    
    protected $validationRules = [
        'delivery_order_id' => 'required',
        'material_id' => 'required',
        'measure_id' => 'required',
        'qunatity' => 'numeric',
        'price' => 'numeric',
        'subtotal'=>'numeric'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $detailDeliveryOrders = Detail_Delivery_Order::all();

        PreviousRoute::setNamedRoute('detail_delivery_orders.index.back');
        return view('detail_delivery_orders.index', compact('detailDeliveryOrders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        $materialList = array();
        $measureList = \App\Measure::select("id","name")->pluck('name', 'id');
        return view('detail_delivery_orders.create',compact('materialList','measureList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $validation = validator()->make($request->all(),$this->validationRules);

        if ( $validation->fails() ) {
            $errors = $validation->errors();
            foreach ($errors->all() as $message) {
                toast()->error($message, __('json.validation_errors') );
            }
            $validation->validate();
        } else{
            toast()->clear();
        }

        $data = Detail_Delivery_Order::create($request->all());

        //Si es una peticion ajax
        if( $request->ajax() ){
            $detail = Detail_Delivery_Order::select("detail_delivery_orders.id","detail_delivery_orders.delivery_order_id",
            "materials.description AS material","measures.name AS measure","detail_delivery_orders.quantity","detail_delivery_orders.price",
            "detail_delivery_orders.subtotal")
            ->join('materials', 'materials.id', '=', 'detail_delivery_orders.material_id')
            ->join('measures', 'measures.id', '=', 'detail_delivery_orders.measure_id')
            ->where('detail_delivery_orders.id','=',$data->id)
            ->first();

            return response()->json($detail);
        } else {
            toast()->success('message', 'Detail_Delivery_Order added!');
    
            return redirect('detail_delivery_order');
        }        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function show($id, Request $request)
    {
        $detailDeliveryOrder = Detail_Delivery_Order::findOrFail($id);

        if( $request->ajax() ){
            //return response()->json($detailDeliveryOrder);
            return view('detail_delivery_orders.show_fields', compact('detailDeliveryOrder'));
        } else {
            return view('detail_delivery_orders.show', compact('detailDeliveryOrder'));
        }
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function edit(Request $request, $id)
    {
        if (empty($id)==false) {
            
            $detailDeliveryOrder = Detail_Delivery_Order::select("detail_delivery_orders.id","detail_delivery_orders.delivery_order_id",
            "detail_delivery_orders.material_id","materials.description AS material","measures.name AS measure","detail_delivery_orders.quantity","detail_delivery_orders.price",
            "detail_delivery_orders.subtotal")
            ->join('materials', 'materials.id', '=', 'detail_delivery_orders.material_id')
            ->join('measures', 'measures.id', '=', 'detail_delivery_orders.measure_id')
            ->where('detail_delivery_orders.id','=',$id)->firstOrFail();

            $materialList = \App\Material::select("id","code","description")
                ->where('id','=',$detailDeliveryOrder['material_id'])
                ->pluck('description', 'id');

            $measureList = \App\Measure::select("id","name")->pluck('name', 'id');
        } else {
            $detailDeliveryOrder = Detail_Delivery_Order::findOrFail($id);
            $materialList = array();
            $measureList = array();
        }
        

        return view('detail_delivery_orders.edit', compact('detailDeliveryOrder','materialList','measureList'));

        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function update($id,Request $request)
    {
        $validation = validator()->make($request->all(),$this->validationRules);

        if ( $validation->fails() ) {
            $errors = $validation->errors();
            foreach ($errors->all() as $message) {
                toast()->error($message, __('json.validation_errors') );
            }
            $validation->validate();
        } else{
            toast()->clear();
        }

        $detailDeliveryOrders = Detail_Delivery_Order::findOrFail($id);
        $detailDeliveryOrders->update($request->all());

        //Si es una peticion ajax
        if( $request->ajax() ){
            $detail = Detail_Delivery_Order::select("detail_delivery_orders.id","detail_delivery_orders.delivery_order_id",
            "materials.description AS material","measures.name AS measure","detail_delivery_orders.quantity","detail_delivery_orders.price",
            "detail_delivery_orders.subtotal")
            ->join('materials', 'materials.id', '=', 'detail_delivery_orders.material_id')
            ->join('measures', 'measures.id', '=', 'detail_delivery_orders.measure_id')
            ->where('detail_delivery_orders.id','=',$id)
            ->first();

            toast()->success('message', 'Detail_Delivery_Order updated!');
            return response()->json($detail);
        } else {
            
            return redirect('detail_delivery_order');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function destroy(Request $request,$id)
    {
        $detailDeliveryOrders = Detail_Delivery_Order::findOrFail($id);

        $detailDeliveryOrders->delete();

        //Si es una peticion ajax
        if( $request->ajax() ){
            return response()->json($detailDeliveryOrders);
        } else {
        Session::flash('message', 'Detail_Delivery_Order deleted!');
        Session::flash('status', 'success');
        }
    }

    /**
     * Show the application dataAjax.
     *
     * @return \Illuminate\Http\Response
     */
    public function dataMaterials(Request $request)
    {
        $data = [];

        if($request->has('q')){
            $search = $request->q;
            $data = DB::table("materials")
                    ->select("id","code","description")
                    ->where('description','LIKE',"%$search%")
                    ->where('deleted_at','=',Null)
                    ->get();
        }
        return response()->json($data);
    } 

    /**
     * Show the application dataAjax.
     *
     * @return \Illuminate\Http\Response
     */
    public function dataMeasures(Request $request)
    {
        $data = [];

        if($request->has('material_id')){
            $search = $request->material_id;
            $data = DB::table("material_measures")
                    ->select("measures.id","measures.name","measures.unit")
                    ->join('measures', 'measures.id', '=', 'material_measures.measure_id')
                    ->where('material_measures.material_id','=',$request->material_id)
                    ->where('material_measures.deleted_at','=',Null)                    
                    ->get();
        }
        return response()->json($data);
    } 

}

resources/views/detail_delivery_orders/create.blade.php
<div class="card-body">
    <div class="col-lg-12">
        {!! Form::open(['route' => 'detail_delivery_order.store','class' => 'form-horizontal','id'=>'frmDetailDeliveryOrder','autocomplete' => 'off']) !!}
        <div class="row">
            @include('detail_delivery_orders.fields')
        </div>
        {!! Form::close() !!}
    </div> <!-- col-12 !-->
</div> <!-- box body !-->

resources/views/detail_delivery_orders/edit.blade.php
<div class="card-body">
    <div class="col-lg-12">
        {!! Form::model($detailDeliveryOrder, ['route' => ['detail_delivery_order.update', $detailDeliveryOrder->id], 'method' => 'patch',
            'class' => 'form-horizontal','id'=>'frmDetailDeliveryOrder','autocomplete' => 'off']) !!}
        <div class="row">   
            @include('detail_delivery_orders.fields')
        </div>
        {!! Form::close() !!}
    </div> <!-- col-12 !-->
</div> <!-- box body !-->

resources/views/detail_delivery_orders/fields.blade.php
<div class="col-md-4">
    <div class="form-group {{ $errors->has('material_id') ? 'has-error' : ''}}">
        {!! Form::label('material_id', 'Material Id: ', ['class' => 'control-label']) !!}
        <div class="">
            @php $material_id = (isset($detailDeliveryOrder->material_id)) ? $detailDeliveryOrder->material_id : null  @endphp
            {!! Form::select('material_id', $materialList, $material_id, ['class'=>'form-control','id'=>'material_id']) !!}
            {!! $errors->first('material_id', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>
<div class="col-md-1">
    <div class="form-group {{ $errors->has('quantity') ? 'has-error' : ''}}">
        {!! Form::label('quantity', 'Cantidad: ', ['class' => 'control-label']) !!}
        <div class="">
            @php $quantity = (isset($detailDeliveryOrder->quantity)) ? $detailDeliveryOrder->quantity : null  @endphp
            {!! Form::text('quantity', $quantity, ['class' => 'form-control','data-cell'=>'DO1']) !!}
            {!! $errors->first('quantity', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>
<div class="col-md-2">
    <div class="form-group {{ $errors->has('measure_id') ? 'has-error' : ''}}">
        {!! Form::label('measure_id', 'Id Medida: ', ['class' => 'control-label']) !!}
        <div class="">
            @php $measure_id = (isset($detailDeliveryOrder->measure_id)) ? $detailDeliveryOrder->measure_id : null  @endphp
            {!! Form::select('measure_id', $measureList, $measure_id, ['class' => 'form-control']) !!}
            {!! $errors->first('measure_id', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>                
<div class="col-md-2">
    <div class="form-group {{ $errors->has('price') ? 'has-error' : ''}}">
        {!! Form::label('price', 'Precio: ', ['class' => 'control-label']) !!}
        <div class="">
            @php $price = (isset($detailDeliveryOrder->price)) ? $detailDeliveryOrder->price : null  @endphp
            {!! Form::number('price', $price, ['class' =>'form-control','step' => 'any','data-cell'=>'DO2', 'data-format'=>"0.00"]) !!}
            {!! $errors->first('price', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>
<div class="col-md-3">
    <div class="form-group {{ $errors->has('subtotal') ? 'has-error' : ''}}">
        {!! Form::label('subtotal', 'Subtotal: ', ['class' => 'control-label']) !!}
        <div class="">
            @php $subtotal = (isset($detailDeliveryOrder->subtotal)) ? $detailDeliveryOrder->subtotal : null  @endphp
            {!! Form::number('subtotal', $subtotal, ['class' => 'form-control','step' => 'any','data-cell'=>'DO3','data-format'=>"0.00",'data-formula'=>'DO1*DO2']) !!}
            {!! $errors->first('subtotal', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

<!-- Submit Field -->
<div class="pull-right">
    @php $id = (isset($detailDeliveryOrder->id)) ? $detailDeliveryOrder->id : null  @endphp
        {!! Form::hidden('id', null, ['class' => 'form-control','placeholder' => 'id']) !!}
    
    @php $param_delivery_order_id = (isset($delivery_order_id)) ? $delivery_order_id : null  @endphp
    @php $delivery_order_id = (isset($detailDeliveryOrder->delivery_order_id)) ? $detailDeliveryOrder->delivery_order_id : $param_delivery_order_id  @endphp
        {!! Form::hidden('delivery_order_id', $delivery_order_id, ['class' => 'form-control','placeholder' => 'delivery_order_id']) !!}

    <a id="save_detailDeliveryOrder" data-id="{{ $id }}" class="btn btn-success">
        <i class="glyphicon glyphicon-pencil"></i> {{__('generic.save')}}
    </a>
</div>

resources/views/detail_delivery_orders/index.blade.php
@extends('layouts.app')

@section('main-content')
    <section class="content-header">
        <h1 class="pull-left">Detail Delivery Orders</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('detail_delivery_order.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="card-body">
                    @include('detail_delivery_orders.table')
            </div>
        </div>
    </div>
@endsection

resources/views/detail_delivery_orders/show.blade.php
@extends('layouts.app')

@section('main-content')
    <section class="content-header">
        <h1>
            Detail Delivery Order
        </h1>
    </section>
    <div class="content">
        <div class="card">
            <div class="card-body">
                <div class="row" style="padding-left: 20px">
                    @include('detail_delivery_orders.show_fields')
                    <a href="{!! route('detail_delivery_order.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/detail_delivery_orders/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
    <p class="form-control-static" >{!! $detailDeliveryOrder->id !!}</p>
    </div>
</div>

<!-- Delivery Order Id Field -->
<div class="form-group">
    {!! Form::label('delivery_order_id', 'Delivery Order Id:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
    <p class="form-control-static" >{!! $detailDeliveryOrder->delivery_order_id !!}</p>
    </div>
</div>

<!-- Material Field -->
<div class="form-group">
    {!! Form::label('material', 'Material:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->material->description !!}</p>
    </div>
</div>

<!-- Measure Id Field -->
<div class="form-group">
    {!! Form::label('measure_id', 'Measure Id:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->measure->name !!}</p>
    </div>
</div>

<!-- Quantity Field -->
<div class="form-group">
    {!! Form::label('quantity', 'Quantity:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->quantity !!}</p>
    </div>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', 'Price:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->price !!}</p>
    </div>
</div>

<!-- Subtotal Field -->
<div class="form-group">
    {!! Form::label('subtotal', 'Subtotal:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->subtotal !!}</p>
    </div>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->created_at !!}</p>
    </div>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        <p class="form-control-static" >{!! $detailDeliveryOrder->updated_at !!}</p>
    </div>
</div>

resources/views/detail_delivery_orders/table.blade.php
<table class="table table-responsive" id="detailDeliveryOrders-table">
    <thead>
        <th>Id</th>
        <th>Delivery Order Id</th>
        <th>Material</th>
        <th>Measure Id</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Subtotal</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($detailDeliveryOrders as $detailDeliveryOrder)
        <tr>
            <td>{!! $detailDeliveryOrder->id !!}</td>
            <td>{!! $detailDeliveryOrder->delivery_order_id !!}</td>
            <td>{!! $detailDeliveryOrder->material->description !!}</td>
            <td>{!! $detailDeliveryOrder->measure->name !!}</td>
            <td>{!! $detailDeliveryOrder->quantity !!}</td>
            <td>{!! $detailDeliveryOrder->price !!}</td>
            <td>{!! $detailDeliveryOrder->subtotal !!}</td>
            <td>
                {!! Form::open(['route' => ['detail_delivery_order.destroy', $detailDeliveryOrder->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('detail_delivery_order.show', [$detailDeliveryOrder->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('detail_delivery_order.edit', [$detailDeliveryOrder->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>